version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: task_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-corenglish}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-corenglish}
      POSTGRES_DB: ${DB_NAME:-corenglish}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-corenglish}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    container_name: task_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - task_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: ${DOCKERHUB_USERNAME:-naufalhakm}/corenglish:latest
    container_name: task_api
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task_network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  worker:
    image: ${DOCKERHUB_USERNAME:-naufalhakm}/corenglish:latest
    container_name: task_worker
    command: ["./worker"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - task_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  task_network:
    driver: bridge